# Generated by Django 5.0.4 on 2024-04-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField()),
                ('attendees', models.IntegerField()),
                ('category', models.CharField(choices=[('CT', 'Concert'), ('CE', 'Conference'), ('G', 'Game')], default='CT', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('status', models.CharField(choices=[('R', 'Reserved'), ('C', 'Cancelled'), ('P', 'Pending')], default='R', max_length=1)),
            ],
        ),
    ]
